services:
  core:
    image: wojiushixiaobai/jms_core:${VERSION}
    container_name: jms_core
    restart: always
    command: start web
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      SECRET_KEY: $SECRET_KEY
      BOOTSTRAP_TOKEN: $BOOTSTRAP_TOKEN
      LOG_LEVEL: $LOG_LEVEL
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
      REDIS_PASSWORD: $REDIS_PASSWORD
      MAGNUS_PORT: ${MAGNUS_PORT:-30000-30020}
      DOMAINS: ${DOMAINS:-}
    healthcheck:
      test: "check http://localhost:8080/api/health/"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    volumes:
      - ${VOLUME_DIR}/core/data:/opt/jumpserver/data
    networks:
      - net

  celery:
    image: wojiushixiaobai/jms_core:${VERSION}
    container_name: jms_celery
    restart: always
    command: start task
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      SECRET_KEY: $SECRET_KEY
      BOOTSTRAP_TOKEN: $BOOTSTRAP_TOKEN
      LOG_LEVEL: $LOG_LEVEL
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
      REDIS_PASSWORD: $REDIS_PASSWORD
      MAGNUS_PORT: ${MAGNUS_PORT:-30000-30020}
      DOMAINS: ${DOMAINS:-}
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "bash /opt/jumpserver/utils/check_celery.sh"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - ${VOLUME_DIR}/core/data:/opt/jumpserver/data
    networks:
      - net

  koko:
    image: wojiushixiaobai/jms_koko:${VERSION}
    container_name: jms_koko
    restart: always
    privileged: true
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      CORE_HOST: http://core:8080
      BOOTSTRAP_TOKEN: $BOOTSTRAP_TOKEN
      LOG_LEVEL: $LOG_LEVEL
      SSHD_PORT: ${SSH_PORT:-2222}
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "check http://localhost:5000/koko/health/"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ${VOLUME_DIR}/koko/data:/opt/koko/data
    ports:
      - ${SSH_PORT:-2222}:${SSH_PORT}
    networks:
      - net

  guacd:
    image: jumpserver/guacd:1.5.5-bookworm
    container_name: jms_guacd
    user: root
    restart: always
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      GUACD_LOG_LEVEL: ${GUACD_LOG_LEVEL:-error}
    volumes:
      - ${VOLUME_DIR}/lion/data:/opt/lion/data
    networks:
      - net

  lion:
    image: wojiushixiaobai/jms_lion:${VERSION}
    container_name: jms_lion
    restart: always
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      CORE_HOST: http://core:8080
      BOOTSTRAP_TOKEN: $BOOTSTRAP_TOKEN
      LOG_LEVEL: $LOG_LEVEL
      GUA_HOST: ${GUA_HOST:-guacd}
      GUA_PORT: ${GUA_PORT:-4822}
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "check http://localhost:8081/lion/health/"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ${VOLUME_DIR}/lion/data:/opt/lion/data
    networks:
      - net

  magnus:
    image: wojiushixiaobai/jms_magnus:${VERSION}
    container_name: jms_magnus
    restart: always
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      CORE_HOST: http://core:8080
      BOOTSTRAP_TOKEN: $BOOTSTRAP_TOKEN
      LOG_LEVEL: $LOG_LEVEL
      MAGNUS_MYSQL_PORT: ${MAGNUS_MYSQL_PORT:-33061}
      MAGNUS_MARIADB_PORT: ${MAGNUS_MARIADB_PORT:-33062}
      MAGNUS_REDIS_PORT: ${MAGNUS_REDIS_PORT:-63790}
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "check http://localhost:8088/health"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ${VOLUME_DIR}/magnus/data:/opt/magnus/data
    ports:
      - ${MAGNUS_MYSQL_PORT:-33061}:33061
      - ${MAGNUS_MARIADB_PORT:-33062}:33062
      - ${MAGNUS_REDIS_PORT:-63790}:63790
    networks:
      - net

  chen:
    image: wojiushixiaobai/jms_chen:${VERSION}
    container_name: jms_chen
    restart: always
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      CORE_HOST: http://core:8080
      BOOTSTRAP_TOKEN: $BOOTSTRAP_TOKEN
      LOG_LEVEL: $LOG_LEVEL
    volumes:
      - ${VOLUME_DIR}/chen/data:/opt/chen/data
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "check http://localhost:8082/chen"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - net

  kael:
    image: wojiushixiaobai/jms_kael:${VERSION}
    container_name: jms_kael
    restart: always
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      CORE_HOST: http://core:8080
      BOOTSTRAP_TOKEN: $BOOTSTRAP_TOKEN
      LOG_LEVEL: $LOG_LEVEL
    volumes:
      - ${VOLUME_DIR}/kael/data:/opt/kael/data
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "check http://localhost:8083/kael/health/"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - net

  web:
    image: wojiushixiaobai/jms_web:${VERSION}
    container_name: jms_web
    restart: always
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      CORE_HOST: http://core:8080
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "check http://localhost/api/health/"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ${VOLUME_DIR}/core/data:/opt/jumpserver/data
      - ${VOLUME_DIR}/web/data/logs:/var/log/nginx
      - ${VOLUME_DIR}/web/download:/opt/download
    ports:
      - ${HTTP_PORT:-80}:${HTTP_PORT:-80}
    networks:
      - net
